framework:
    rate_limiter:
        api_auth:
            policy: 'sliding_window'
            limit: 5
            interval: '10 minute'

        api_refresh:
            policy: 'sliding_window'
            limit: 30
            interval: '15 minute'

        api_read:
            policy: sliding_window
            limit: 100
            interval: '1 minute'

        api_write:
            policy: sliding_window
            limit: 30
            interval: '1 minute'

        api_reports:
            policy: 'sliding_window'
            limit: 20
            interval: '1 minute'
