# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters: {}

services:
    # ----------------------------------
    # Defaults for all services
    # ----------------------------------
    _defaults:
        autowire: true
        autoconfigure: true

    # ----------------------------------
    # Automatically register services
    # ----------------------------------
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'


    # ----------------------------------
    # Event listeners
    # ----------------------------------
    App\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    App\EventListener\BudgetAlertListener:
        tags:
            - { name: kernel.event_listener, event: App\Event\TransactionCreatedEvent, method: onTransactionCreated }

    App\EventListener\RateLimitListener:
        arguments:
            $apiReadLimiter: '@limiter.api_read'
            $apiReportsLimiter: '@limiter.api_reports'
            $apiAuthLimiter: '@limiter.api_auth'
            $apiWriteLimiter: '@limiter.api_write'
            $apiRefreshLimiter: '@limiter.api_refresh'
        tags:
            - { name: kernel.event_listener, event: kernel.request }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    App\Service\NotificationServiceInterface:
        alias: App\Service\LoggerNotificationService
